from typing import Protocol

from src.core.novel.models.novel import Novel, NovelPage
from src.core.novel.models.step import NovelStep


class NovelProviderProtocol(Protocol):
    async def get(self, novel_id: int) -> Novel: ...
    async def list(self, limit: int, offset: int) -> NovelPage: ...
    async def delete(self, novel_id: int) -> None: ...
    async def get_step(self, novel_id: int, offset: int | None) -> NovelStep: ...
