"""Add novels model

Revision ID: f2c2b0462f15
Revises: 
Create Date: 2026-08-17 19:12:25.902965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c2b0462f15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novels',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('public_description', sa.String(), nullable=False),
    sa.Column('tone', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novels_id'), 'novels', ['id'], unique=False)
    op.create_table('characters',
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('arc', sa.String(), nullable=False),
    sa.Column('voice_notes', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_table('roadmap',
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('target_choice', sa.Boolean(), nullable=False),
    sa.Column('choice_stakes', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_id'), 'roadmap', ['id'], unique=False)
    op.create_table('scenes',
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_id'), 'scenes', ['id'], unique=False)
    op.create_index(op.f('ix_scenes_roadmap_id'), 'scenes', ['roadmap_id'], unique=False)
    op.create_table('dialogue_lines',
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('is_final_for_roadmap', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogue_lines_character_id'), 'dialogue_lines', ['character_id'], unique=False)
    op.create_index(op.f('ix_dialogue_lines_id'), 'dialogue_lines', ['id'], unique=False)
    op.create_index(op.f('ix_dialogue_lines_novel_id'), 'dialogue_lines', ['novel_id'], unique=False)
    op.create_index(op.f('ix_dialogue_lines_scene_id'), 'dialogue_lines', ['scene_id'], unique=False)
    op.create_table('dialogue_actions',
    sa.Column('dialogue_line_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('next_roadmap_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dialogue_line_id'], ['dialogue_lines.id'], ),
    sa.ForeignKeyConstraint(['next_roadmap_id'], ['roadmap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogue_actions_dialogue_line_id'), 'dialogue_actions', ['dialogue_line_id'], unique=False)
    op.create_index(op.f('ix_dialogue_actions_id'), 'dialogue_actions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialogue_actions_id'), table_name='dialogue_actions')
    op.drop_index(op.f('ix_dialogue_actions_dialogue_line_id'), table_name='dialogue_actions')
    op.drop_table('dialogue_actions')
    op.drop_index(op.f('ix_dialogue_lines_scene_id'), table_name='dialogue_lines')
    op.drop_index(op.f('ix_dialogue_lines_novel_id'), table_name='dialogue_lines')
    op.drop_index(op.f('ix_dialogue_lines_id'), table_name='dialogue_lines')
    op.drop_index(op.f('ix_dialogue_lines_character_id'), table_name='dialogue_lines')
    op.drop_table('dialogue_lines')
    op.drop_index(op.f('ix_scenes_roadmap_id'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_roadmap_id'), table_name='roadmap')
    op.drop_table('roadmap')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_novels_id'), table_name='novels')
    op.drop_table('novels')
    # ### end Alembic commands ###
