"""Add GenerationJob model

Revision ID: 099970decd50
Revises: 
Create Date: 2026-10-01 11:48:35.128182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '099970decd50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('kind', sa.Enum('novel', 'scene', name='jobkind', native_enum=False, length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedup_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('created', 'publishing', 'sent', 'done', 'failed', name='jobstatus', length=None), server_default='created', nullable=False),
    sa.Column('result_id', sa.Uuid(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_jobs_id'), 'generation_jobs', ['id'], unique=False)
    op.create_index('uq_active_job', 'generation_jobs', ['kind', 'dedup_key'], unique=True, postgresql_where=sa.text("status IN ('created', 'publishing', 'sent')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_job', table_name='generation_jobs', postgresql_where=sa.text("status IN ('created', 'publishing', 'sent')"))
    op.drop_index(op.f('ix_generation_jobs_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    # ### end Alembic commands ###
