from typing import Protocol

from src.core.novels.models import Novel, Character, Roadmap, DialogueAction, DialogueLine


class DialogueActionProtocol(Protocol):
    async def add(self, dialog_action: DialogueAction) -> DialogueAction: ...
    async def get_by_id(self, dialog_action_id: int) -> DialogueAction | None: ...
    async def delete(self, dialog_action_id: int) -> None: ...


class DialogueLineRepositoryProtocol(Protocol):
    async def add(self, dialog_line: DialogueLine) -> DialogueLine: ...
    async def get_by_id(self, dialog_line_id: int) -> DialogueLine | None: ...
    async def list_by_novel_id(self, novel_id: int) -> list[DialogueLine]: ...
    async def delete(self, dialog_line_id: int) -> None: ...


class RoadmapRepositoryProtocol(Protocol):
    async def add(self, roadmap: Roadmap) -> Roadmap: ...
    async def get_by_id(self, roadmap_id: int) -> Roadmap | None: ...
    async def list_by_novel_id(self, novel_id: int) -> list[Roadmap]: ...
    async def delete(self, roadmap_id: int) -> None: ...


class CharacterRepositoryProtocol(Protocol):
    async def add(self, character: Character) -> Character: ...
    async def get_by_id(self, character_id: int) -> Character | None: ...
    async def list_by_novel_id(self, novel_id: int) -> list[Character]: ...
    async def delete(self, character_id: int) -> None: ...


class NovelRepositoryProtocol(Protocol):
    async def add(self, novel: Novel) -> Novel: ...
    async def get_by_id(self, novel_id: int) -> Novel | None: ...
    async def list_all(self) -> list[Novel]: ...
    async def delete(self, novel_id: int) -> None: ...


class NovelGeneratorProtocol(Protocol):
    async def generate(self, prompt: list) -> dict:
        """Возвращает (title, description) на основе пожелания пользователя."""
        ...
