from typing import Protocol

from src.core.novels.models import Novel


class NovelRepositoryProtocol(Protocol):
    async def add(self, novel: Novel) -> Novel: ...
    async def get_by_id(self, novel_id: int) -> Novel | None: ...
    async def list_all(self) -> list[Novel]: ...
    async def delete(self, novel_id: int) -> None: ...

class NovelGeneratorProtocol(Protocol):
    async def generate(self, prompt: list) -> tuple[str, str]:
        """Возвращает (title, description) на основе пожелания пользователя."""
        ...